apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: polyfea-controller
  namespace: polyfea
spec:
  wait: true

  interval: 3m
  path: controller
  components:
    - ./components/postbuild
  prune: true
  sourceRef:
    kind: GitRepository
    name: polyfea-gitops-repository

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: polyfea-shell-cfg
        optional: true