apiVersion: polyfea.github.io/v1alpha1
kind: MicroFrontendClass
metadata:
  name: md-shell
spec:
  routing:
    parentRefs:
      - kind: Gateway
        name: ${GATEWAY_NAME:=polyfea-gateway}
        namespace: ${GATEWAY_NAMESPACE:=polyfea}