apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: material-shell
  namespace: polyfea
spec:
  wait: true
  interval: 30m
  path: md-shell
  prune: true
  sourceRef:
    kind: GitRepository
    name: polyfea-gitops-repository
# patch to enable postbuild configuration
patches:
    - patch: |-
        spec:
          title: ${APP_TITLE:=Polyfea Microfrontend MD Shell}
          baseUri: ${APP_BASE_URI:=/fea}
          progressiveWebApp:
            webAppManifest:
              name: ${APP_TITLE:=Polyfea Microfrontend MD Shell}
              start_url: ${APP_BASE_URI:=/fea}
          cspHeader: ${CSP_HEADER:=default-src 'self'; font-src 'self'; script-src 'strict-dynamic' 'nonce-{NONCE_VALUE}'; worker-src 'self'; manifest-src 'self'; style-src 'self' 'strict-dynamic' 'nonce-{NONCE_VALUE}'; style-src-attr 'self' 'unsafe-inline'; img-src *;}
      target:
        apiVersion: polyfea.github.io/v1alpha1
        kind: MicroFrontendClass
        name: material-shell

postBuild:
  substituteFrom:
    - kind: ConfigMap
      name: polyfea-shell-cfg
      optional: true
    