apiVersion: polyfea.github.io/v1alpha1
kind: MicroFrontendClass
metadata:
  name: md-shell
spec:
  title: ${APP_TITLE:=Polyfea Microfrontend MD Shell}
  baseUri: ${APP_BASE_URI:=/fea}
  progressiveWebApp:
    webAppManifest:
      name: ${APP_TITLE:=Polyfea Microfrontend MD Shell}
      start_url: ${APP_BASE_URI:=/fea}
  cspHeader: ${CSP_HEADER:=null}
