---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: polyfea-polyfea-controller-manager
  labels:
    helm.sh/chart: polyfea-controller-0.5.1
    app.kubernetes.io/name: polyfea-controller
    app.kubernetes.io/instance: polyfea
    app.kubernetes.io/version: "v0.4.1"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - polyfea.github.io
  resources:
  - microfrontendclasses
  - microfrontends
  - webcomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - polyfea.github.io
  resources:
  - microfrontendclasses/finalizers
  - microfrontends/finalizers
  - webcomponents/finalizers
  verbs:
  - update
- apiGroups:
  - polyfea.github.io
  resources:
  - microfrontendclasses/status
  - microfrontends/status
  - webcomponents/status
  verbs:
  - get
  - patch
  - update