---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: polyfea-controller
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - polyfea.github.io
  resources:
  - microfrontendclasses
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - polyfea.github.io
  resources:
  - microfrontendclasses/finalizers
  verbs:
  - update
  - patch
- apiGroups:
  - polyfea.github.io
  resources:
  - microfrontendclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - polyfea.github.io
  resources:
  - microfrontends
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - polyfea.github.io
  resources:
  - microfrontends/finalizers
  verbs:
  - update
  - patch
- apiGroups:
  - polyfea.github.io
  resources:
  - microfrontends/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - polyfea.github.io
  resources:
  - webcomponents
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - polyfea.github.io
  resources:
  - webcomponents/finalizers
  verbs:
  - update
  - patch
- apiGroups:
  - polyfea.github.io
  resources:
  - webcomponents/status
  verbs:
  - get
  - patch
  - update
