apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: polyfea-polyfea-controller-manager
  labels:
    app.kubernetes.io/name: polyfea-controller
    app.kubernetes.io/instance: polyfea
    app.kubernetes.io/version: "v0.4.1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: polyfea-polyfea-controller-manager
subjects:
- kind: ServiceAccount
  name: polyfea-polyfea-controller