apiVersion: v1
kind: ServiceAccount
metadata:
  name: polyfea-controller
  labels:
    app.kubernetes.io/name: polyfea-controller
    app.kubernetes.io/instance: polyfea
    app.kubernetes.io/version: "v0.5.4"
