apiVersion: v1
kind: ServiceAccount
metadata:
  name: polyfea-polyfea-controller
  labels:
    helm.sh/chart: polyfea-controller-0.5.1
    app.kubernetes.io/name: polyfea-controller
    app.kubernetes.io/instance: polyfea
    app.kubernetes.io/version: "v0.4.1"
    app.kubernetes.io/managed-by: Helm