apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: home-fea
  labels:
    app.kubernetes.io/name: polyfea-md-shell-samples
    app.kubernetes.io/instance: polyfea
    app.kubernetes.io/version: "2.0.4"
spec:
  microFrontend: polyfea-md-shell
  element: polyfea-md-app
  attributes: 
    - name: headline
      value: Home page
    - name: short-headline
      value: Home
    - name: supporting-text
      value: Go to landing page of the Polyfea Shell Application.
    - name: material-icon
      value: home
    - name: href
      value: ./
  priority: 100
  displayRules:
    - anyOf:
      - context-name: rail-content
      - context-name: drawer-content
      - context-name: navigation-content