apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: polyfea
resources:
- applications.webcomponent.yaml
- deployment.yaml
- home-fea.webcomponent.yaml
- material.microfrontend.yaml
- md-shell.microfrontend.yaml
- md-shell.webcomponent.yaml
- service.yaml
- microfrontendclass.yaml

labels:
  - pairs:
      polyfea.github.io/feature-set: polyfea-md-shell