apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: polyfea-md-shell
  labels:
    app.kubernetes.io/name: polyfea-md-shell-samples
    app.kubernetes.io/instance: polyfea
    app.kubernetes.io/version: "2.0.4"
spec:
  microFrontend: polyfea-md-shell
  element: polyfea-md-shell
  attributes: 
    - name: application-headline
      value: "Polyfea Shell Application"
    - name: locale-menu
      value: "true"
    - name: locales
      value: '"en", "sk", "cz", "de", "es", "fr"]'
    - name: theme-menu
      value: "true"
    - name: absolute-position
      value: "true"
  displayRules:
    - anyOf:
      - context-name: shell

# The polyfea-md-shell adds context areas: 
# * drawer-content -Navigation drawer icons.
# * main-content -The main content area of the page.
# * navigation-content -The navigation bar icons.
# * rail-content- The navigation rail icons.
# * rail-primary-action - The primary action of the rail
# * topbar-leading-icon - The leading icon of the top bar.
# * topbar-menu-items - The top bar's menu items.
# * topbar-trailing-icon - The trailing icon area of the top bar.

