apiVersion: polyfea.github.io/v1alpha1
kind: MicroFrontendClass
metadata:
  name: md-shell
  labels:
    app.kubernetes.io/name: polyfea-md-shell-samples
    app.kubernetes.io/instance: polyfea
    app.kubernetes.io/version: "2.0.4"
spec:
  title: "Polyfea Microfrontend MD Shell"
  baseUri: "/fea"
  namespacePolicy:
    from: All
  extraMetaTags:
  - name: viewport
    content: width=device-width, initial-scale=1
  progressiveWebApp:
    webAppManifest:
      name: "Polyfea MD Shell"
      start_url: "/fea"
      display: "standalone"
      icons:
        - src: "https://avatars.githubusercontent.com/u/154217229?s=400&u=ae64608e9686a2405680676a15800dc2b6df32bb&v=4"
          sizes: "128x128"
          type: "image/png"
    cacheOptions:
      preCache:
        - url: polyfea/boot.mjs
      cacheRoutes:
        - pattern: .*.jpg
  cspHeader: >-
    default-src 'self'; font-src 'self'; script-src 'strict-dynamic'
    'nonce-{NONCE_VALUE}'; worker-src 'self'; manifest-src 'self'; style-src
    'self' 'unsafe-inline'; style-src-attr 'self'
    'unsafe-inline'; img-src *; connect-src *;